export const LANGUAGE_OPTIONS = [
  { value: "afrikaans", label: "Afrikaans" },
  { value: "akan", label: "Akan" },
  { value: "amharic", label: "Amharic" },
  { value: "arabic (standard)", label: "Arabic (Standard)" },
  { value: "assamese", label: "Assamese" },
  { value: "azerbaijani", label: "Azerbaijani" },
  { value: "belarusian", label: "Belarusian" },
  { value: "bengali", label: "Bengali" },
  { value: "bhojpuri", label: "Bhojpuri" },
  { value: "bulgarian", label: "Bulgarian" },
  { value: "burmese", label: "Burmese" },
  { value: "cebuano", label: "Cebuano" },
  { value: "central khmer (khmer)", label: "Central Khmer (Khmer)" },
  { value: "chhattisgarhi", label: "Chhattisgarhi" },
  { value: "chichewa", label: "Chichewa" },
  { value: "chittagonian", label: "Chittagonian" },
  { value: "czech", label: "Czech" },
  { value: "danish", label: "Danish" },
  { value: "deccan (dakhini)", label: "Deccan (Dakhini)" },
  { value: "dhundhari", label: "Dhundhari" },
  { value: "dutch", label: "Dutch" },
  { value: "eastern farsi (dari)", label: "Eastern Farsi (Dari)" },
  { value: "eastern punjabi", label: "Eastern Punjabi" },
  { value: "egyptian arabic", label: "Egyptian Arabic" },
  { value: "english", label: "English" },
  { value: "finnish", label: "Finnish" },
  { value: "french", label: "French" },
  { value: "german", label: "German" },
  { value: "greek", label: "Greek" },
  { value: "gujarati", label: "Gujarati" },
  { value: "haitian creole", label: "Haitian Creole" },
  { value: "hakka chinese", label: "Hakka Chinese" },
  { value: "hausa", label: "Hausa" },
  { value: "haryanvi", label: "Haryanvi" },
  { value: "hebrew", label: "Hebrew" },
  { value: "hiligaynon (ilonggo)", label: "Hiligaynon (Ilonggo)" },
  { value: "hindi", label: "Hindi" },
  { value: "hungarian", label: "Hungarian" },
  { value: "ilocano", label: "Ilocano" },
  { value: "indonesian", label: "Indonesian" },
  { value: "italian", label: "Italian" },
  { value: "japanese", label: "Japanese" },
  { value: "javanese", label: "Javanese" },
  { value: "jin chinese", label: "Jin Chinese" },
  { value: "kannada", label: "Kannada" },
  { value: "kazakh", label: "Kazakh" },
  { value: "khmer", label: "Khmer" },
  { value: "kinyarwanda", label: "Kinyarwanda" },
  { value: "kongo", label: "Kongo" },
  { value: "korean", label: "Korean" },
  {
    value: "kurmanji (northern kurdish)",
    label: "Kurmanji (Northern Kurdish)",
  },
  { value: "lao", label: "Lao" },
  { value: "lingala", label: "Lingala" },
  { value: "lithuanian", label: "Lithuanian" },
  { value: "lombard", label: "Lombard" },
  { value: "magahi", label: "Magahi" },
  { value: "maithili", label: "Maithili" },
  { value: "malagasy", label: "Malagasy" },
  { value: "malay (malaysian)", label: "Malay (Malaysian)" },
  { value: "mandarin chinese", label: "Mandarin Chinese" },
  { value: "marathi", label: "Marathi" },
  { value: "marwari", label: "Marwari" },
  { value: "mesopotamian arabic", label: "Mesopotamian Arabic" },
  { value: "min nan chinese", label: "Min Nan Chinese" },
  {
    value: "napoletano-calabrese (neapolitan)",
    label: "Napoletano-Calabrese (Neapolitan)",
  },
  { value: "najdi arabic", label: "Najdi Arabic" },
  { value: "nepali", label: "Nepali" },
  { value: "nigerian fulfulde (fula)", label: "Nigerian Fulfulde (Fula)" },
  { value: "nigerian pidgin", label: "Nigerian Pidgin" },
  { value: "north levantine arabic", label: "North Levantine Arabic" },
  {
    value: "northern min (min bei chinese)",
    label: "Northern Min (Min Bei Chinese)",
  },
  { value: "northern pashto", label: "Northern Pashto" },
  { value: "northern zhuang", label: "Northern Zhuang" },
  { value: "norwegian", label: "Norwegian" },
  { value: "odia (oriya)", label: "Odia (Oriya)" },
  { value: "oromo (west-central oromo)", label: "Oromo (West-Central Oromo)" },
  { value: "pashto", label: "Pashto" },
  { value: "persian (farsi)", label: "Persian (Farsi)" },
  { value: "polish", label: "Polish" },
  { value: "portuguese", label: "Portuguese" },
  { value: "quechua", label: "Quechua" },
  { value: "romanian", label: "Romanian" },
  { value: "russian", label: "Russian" },
  { value: "sanaani arabic", label: "Sanaani Arabic" },
  { value: "saraiki", label: "Saraiki" },
  { value: "serbian", label: "Serbian" },
  { value: "shona", label: "Shona" },
  { value: "sinhala (sinhalese)", label: "Sinhala (Sinhalese)" },
  { value: "slovak", label: "Slovak" },
  { value: "slovene", label: "Slovene" },
  { value: "somali", label: "Somali" },
  { value: "southern pashto", label: "Southern Pashto" },
  { value: "spanish", label: "Spanish" },
  { value: "sudanese arabic", label: "Sudanese Arabic" },
  { value: "sunda", label: "Sunda" },
  { value: "swahili", label: "Swahili" },
  { value: "swedish", label: "Swedish" },
  { value: "tagalog (filipino)", label: "Tagalog (Filipino)" },
  { value: "tajik", label: "Tajik" },
  { value: "tamil", label: "Tamil" },
  { value: "tatar", label: "Tatar" },
  { value: "telugu", label: "Telugu" },
  { value: "thai", label: "Thai" },
  { value: "tigrinya", label: "Tigrinya" },
  { value: "tswana", label: "Tswana" },
  { value: "tunisian arabic", label: "Tunisian Arabic" },
  { value: "turkish", label: "Turkish" },
  { value: "turkmen", label: "Turkmen" },
  { value: "urdu", label: "Urdu" },
  { value: "uyghur", label: "Uyghur" },
  { value: "uzbek", label: "Uzbek" },
  { value: "vietnamese", label: "Vietnamese" },
  { value: "western punjabi", label: "Western Punjabi" },
  { value: "wu chinese", label: "Wu Chinese" },
  { value: "xhosa", label: "Xhosa" },
  { value: "yoruba", label: "Yoruba" },
  { value: "yue chinese (cantonese)", label: "Yue Chinese (Cantonese)" },
  { value: "zulu", label: "Zulu" },
];
